name = "DEVGRU MC"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bf17d6ca1abd8e36f554afdb4ba4b35ce831f82aa1473bad3ec0c438cc8e944"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
