name = "DEVGRU MC"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8380b68db3e2183271b7de6b30445a17033b811e6a16caef001eb5e1c0b27c9"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
