name = "DEVGRU MC"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70e32d2d61589320c451dd49daee1f9e35dba602f256cc61ce72a5b4c965b357"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
